### ISSUE TITLE
Can this library actual decode mp3 data?

### ISSUE THREAD

**Issue by nampdn** [ScottMichaud/AudioSampleLoader#1]
I want to decode MP3 player on the browser, will this help that?

**Comment by ScottMichaud** [comment]
I'm not clear on your exact use case. If you provide a few more details, I might be able to help a little further.

That said, this library takes addresses (URLs) of sound files, downloads them, sends them to Web Audio API to decode them into AudioBuffers, and gives those AudioBuffers to you. Those AudioBuffers can be played, combined, manipulated, and so forth. This is useful for games, media players, audio (and video) editors, and so forth.

Explanation of what an AudioBuffer is:
https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer

It supports any file format that the browser it's running on supports. You can pretty much guarantee that MP3 support will be available in Firefox, Chrome, or Safari on Windows (Vista or later) or Mac. Linux should be fine, too. Firefox and Chrome on Android should also be okay.

**Comment by nampdn** [comment]
My use case is simple, as you know MP3 Frame contains the header and data, my MP3 file was modified at the data of the frame. I just XOR every bit  of it by `0x...`. In order to play, I must XOR every bit again before the decoder run and play it in the browser.

**Comment by ScottMichaud** [comment]
Okay, it sounds like AudioSampleLoader won't help your situation. It doesn't modify the file, and it's not designed to let you modify the blob before it sends it to Web Audio API.

Its goal is to reduce the loading of audio sources to a single step. For instance, a game needs to grab a batch of footstep/jump/movement sounds or something.

It sounds like you need to use FileReader API.
https://developer.mozilla.org/en-US/docs/Web/API/FileReader

If I understand correctly, you should be able to get an ArrayBuffer representing your file, do your logic (XOR) to the ArrayBuffer, then pass it to an AudioContext's decodeAudioData() to create your AudioBuffer.

**Comment by nampdn** [comment]
Thanks for your recommend.

**Comment by ScottMichaud** [comment]
Hope I helped. I'll leave the issue open for a couple weeks in case you have any follow-up questions.
