### ISSUE TITLE
send() appears to do nothing

### ISSUE THREAD

**Issue by vcrepin** [ScottMichaud/AudioSampleLoader#2]
Hello. I created an ionic project like : https://www.airpair.com/ionic-framework/posts/using-web-audio-api-for-precision-audio-in-ionic

When I call send() it does not fire the success nor the error callback. And when trying to play de sound it complains that the buffer is undefined. 

Is there a way to debug the calls ?

Thanks.

**Comment by ScottMichaud** [comment]
Odd.

What the class does is accepts a URL (or list of URLs), sends it to XHR, sends the result(s) of XHR result to the audio context, and sends its results to the class. If all success callbacks return, then it calls whatever function you attach to `.onload` to let you know that you can access the buffers. If any error callbacks return, then it calls the function attached to `.onerror`.

So, unless you accidentally overwrote one of the functions, like send, then either XHR or the audio context failed silently.

First question -- which browser are you using?
Second question -- does your browser console say anything? I have quite a few console.onerror statements throughout the class.

**Comment by vcrepin** [comment]
Ok, my console was disabled. I enabled it and my problem was that the audio file had no extension...

I'm using Crosswalk.

Thank you very much

**Comment by ScottMichaud** [comment]
No problem! Glad I could help.
